// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package railway

import (
	"context"
	"reflect"

	"example.com/pulumi-railway/sdk/go/railway/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ServiceSource struct {
}

// ServiceSourceInput is an input type that accepts ServiceSourceArgs and ServiceSourceOutput values.
// You can construct a concrete instance of `ServiceSourceInput` via:
//
//	ServiceSourceArgs{...}
type ServiceSourceInput interface {
	pulumi.Input

	ToServiceSourceOutput() ServiceSourceOutput
	ToServiceSourceOutputWithContext(context.Context) ServiceSourceOutput
}

type ServiceSourceArgs struct {
}

func (ServiceSourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceSource)(nil)).Elem()
}

func (i ServiceSourceArgs) ToServiceSourceOutput() ServiceSourceOutput {
	return i.ToServiceSourceOutputWithContext(context.Background())
}

func (i ServiceSourceArgs) ToServiceSourceOutputWithContext(ctx context.Context) ServiceSourceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceSourceOutput)
}

func (i ServiceSourceArgs) ToServiceSourcePtrOutput() ServiceSourcePtrOutput {
	return i.ToServiceSourcePtrOutputWithContext(context.Background())
}

func (i ServiceSourceArgs) ToServiceSourcePtrOutputWithContext(ctx context.Context) ServiceSourcePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceSourceOutput).ToServiceSourcePtrOutputWithContext(ctx)
}

// ServiceSourcePtrInput is an input type that accepts ServiceSourceArgs, ServiceSourcePtr and ServiceSourcePtrOutput values.
// You can construct a concrete instance of `ServiceSourcePtrInput` via:
//
//	        ServiceSourceArgs{...}
//
//	or:
//
//	        nil
type ServiceSourcePtrInput interface {
	pulumi.Input

	ToServiceSourcePtrOutput() ServiceSourcePtrOutput
	ToServiceSourcePtrOutputWithContext(context.Context) ServiceSourcePtrOutput
}

type serviceSourcePtrType ServiceSourceArgs

func ServiceSourcePtr(v *ServiceSourceArgs) ServiceSourcePtrInput {
	return (*serviceSourcePtrType)(v)
}

func (*serviceSourcePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceSource)(nil)).Elem()
}

func (i *serviceSourcePtrType) ToServiceSourcePtrOutput() ServiceSourcePtrOutput {
	return i.ToServiceSourcePtrOutputWithContext(context.Background())
}

func (i *serviceSourcePtrType) ToServiceSourcePtrOutputWithContext(ctx context.Context) ServiceSourcePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceSourcePtrOutput)
}

type ServiceSourceOutput struct{ *pulumi.OutputState }

func (ServiceSourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceSource)(nil)).Elem()
}

func (o ServiceSourceOutput) ToServiceSourceOutput() ServiceSourceOutput {
	return o
}

func (o ServiceSourceOutput) ToServiceSourceOutputWithContext(ctx context.Context) ServiceSourceOutput {
	return o
}

func (o ServiceSourceOutput) ToServiceSourcePtrOutput() ServiceSourcePtrOutput {
	return o.ToServiceSourcePtrOutputWithContext(context.Background())
}

func (o ServiceSourceOutput) ToServiceSourcePtrOutputWithContext(ctx context.Context) ServiceSourcePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceSource) *ServiceSource {
		return &v
	}).(ServiceSourcePtrOutput)
}

type ServiceSourcePtrOutput struct{ *pulumi.OutputState }

func (ServiceSourcePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceSource)(nil)).Elem()
}

func (o ServiceSourcePtrOutput) ToServiceSourcePtrOutput() ServiceSourcePtrOutput {
	return o
}

func (o ServiceSourcePtrOutput) ToServiceSourcePtrOutputWithContext(ctx context.Context) ServiceSourcePtrOutput {
	return o
}

func (o ServiceSourcePtrOutput) Elem() ServiceSourceOutput {
	return o.ApplyT(func(v *ServiceSource) ServiceSource {
		if v != nil {
			return *v
		}
		var ret ServiceSource
		return ret
	}).(ServiceSourceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceSourceInput)(nil)).Elem(), ServiceSourceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceSourcePtrInput)(nil)).Elem(), ServiceSourceArgs{})
	pulumi.RegisterOutputType(ServiceSourceOutput{})
	pulumi.RegisterOutputType(ServiceSourcePtrOutput{})
}
